[project]
name = "navigation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.4",
    "pynavmesh",
    "trimesh>=4.6.6",
]
